version: "3.9"

services:
  app:
    build: .
    container_name: taxi_fare_prediction_bot
    env_file:
      - .env
    image: taxi_fare_prediction_bot:latest
    ports:
      - "8080:8080"

    command: ["python", "app/main.py"]
    volumes:
      - ./logs:/project/logs
    develop:
      watch:
        - action: sync
          path: ./app
          target: /project/app

        - action: sync
          path: ./logging.yaml
          target: /project/logging.yaml

        - action: rebuild
          path: ./pyproject.toml
    